### PR TITLE
Update about page to remove Jarrod and add description for kball

### PR DESCRIPTION
**Pull request by kball**
Since Jarrod is no longer an organizer :( removing him from about page.

Also remedying long lack of description for kball on about page.

### CODE REVIEW

**Comment by smathson** [comment]
Just curious, is Patrick still an organizer?

**Comment by kball** [comment]
Good point, we should probably take him off as well.  I'll have time to do that later, or if you want to move ahead with it go for it.

**Comment by smathson** [comment]
Removed Patrick and added myself (long overdue).

**Comment by smathson** [comment]
Updated a few other places that we had outdated information.

**Comment by kball** [comment]
Looks good to me, but let's get someone who didn't contribute to it to take a look & merge :)

cc @treyhunner @hbrysiewicz

**Pull request merged**
