### PR TITLE
Military_messaging_js_dev_job

### PR DESCRIPTION
**Pull request by Neutron**

### CODE REVIEW

**Comment by hbrysiewicz** [comment]
+1 - if another organizer could review and merge, that would be great :smile_cat:

**Comment by treyhunner** [comment]
@Neutron the NIEM links go to a 404 page: https://www.niem.gov/Pages/default.asp

:+1: once that is resolved

**Comment by Neutron** [comment]
Thanks Trey - fixed it.

**Comment by kball** [comment]
OK looks good

**Pull request merged**
